apiVersion : apps/v1
kind: Deployment
metadata:
  name: mimasisjipipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimasisjipipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: mimasisjipipelinesjavascriptdocker 
    spec:
      containers:
        - name: mimasisjipipelinesjavascriptdocker 
          image: containerregistryadoaksdemo.azurecr.io/mimasisjipipelinesjavascriptdocker
          ports:
          - containerPort: 8080